CREATE DATABASE JSadvClass DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE JSadvClass;

CREATE TABLE IF NOT EXISTS contact (
	id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        fname VARCHAR(50),
        lname VARCHAR(50),
	email VARCHAR(150),
        phone VARCHAR(15),
        address1 VARCHAR(250),
        address2 VARCHAR(250),
        city VARCHAR(100),
        state VARCHAR(2),
        zip VARCHAR(5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS login (
	id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,        
        username VARCHAR(50) NOT NULL UNIQUE KEY,
        password VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;

